### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Luchanso** [Luchanso/lowcost-sapsan#2]
- [ ] GraphQL
- [ ] Apache Cassandra
- [ ] Docker Image
- [ ] Node env api
- [x] Optimisation grab from rzd (remove puppeter)
- [x] Optimisation first run
- [ ] Filters (by price)
- [ ] Mobile friendly
- [ ] Add links to ticket page
- [ ] Make direction switcher
- [x] Saving theme switcher in localstorage
